site_name: skeleton
repo_url: REPO_URL
repo_name: Repository
site_description: skeleton sample for nodejs
theme: readthedocs

nav:
  - Home: "index.md"
  - Readme: "readme.md"

markdown_extensions:
  # - kroki:
  #     ServerURL: /api/proxy/kroki
  - toc:
      baselevel: 2
  - plantuml_markdown
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tabbed
  - markdown_inline_graphviz
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
      use_pygments: true

  - pymdownx.superfences

plugins:
  - techdocs-core
  - search
  - kroki
  - diagrams:
      file_extension: ".diagrams.py"
      max_workers: 5

extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
